################
#    MAKEFILE
################


# Compiler : 
CC=g++
# FLAGS
CCFLAFS=`root-config --cflags --libs` 
# TARGET
TRGT=interaction



INCLUDES+= I$(ROOTSYS)/include -I..

all : $(TRGT)

$(TRGT):
	$(CC) -c lib/stock.h lib/stock.cxx `root-config --cflags --libs`
	$(CC)  interaction.cxx lib/stock.o -o $(TRGT) `root-config --cflags --libs`      

clean:
	rm -fr *.o stock
	rm -fr interaction